- name: Create haproxy quadlet volume
  ansible.builtin.copy:
    content: |
      [Volume]
    dest: "{{ quadlet_user_info.containers_dir }}/haproxy.volume"
    owner: "{{ quadlet_user_info.name }}"
    group: "{{ quadlet_user_info.name }}"
    mode: u=rw,g=r,o=r

- name: Start haproxy volume
  ansible.builtin.systemd_service:
    name: haproxy-volume.service
    daemon_reload: true
    state: started
    scope: user
  environment:
    XDG_RUNTIME_DIR: "{{ quadlet_user_info.xdg_runtime_dir }}"

- name: Create haproxy config
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ quadlet_user_info.volumes_dir }}/systemd-haproxy/_data/haproxy.cfg"
    owner: "{{ quadlet_user_info.name }}"
    group: "{{ quadlet_user_info.name }}"
    mode: u=rw,g=,o=
  notify: Reload haproxy

- name: Create haproxy keepalived config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_conf_dir }}/haproxy.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=
  become: true
  notify: Restart keepalived

- name: Create haproxy sockets
  ansible.builtin.template:
    src: "{{ item }}.socket.j2"
    dest: "{{ quadlet_user_info.systemd_dir }}/{{ item }}.socket"
    owner: "{{ quadlet_user_info.name }}"
    group: "{{ quadlet_user_info.name }}"
    mode: u=rw,g=r,o=r
  loop:
  - haproxy
  - haproxy-monitor
  loop_control:
    label: "{{ item }}"
  notify: Restart haproxy

- name: Create haproxy quadlet container
  ansible.builtin.template:
    src: haproxy.container.j2
    dest: "{{ quadlet_user_info.containers_dir }}/haproxy.container"
    owner: "{{ quadlet_user_info.name }}"
    group: "{{ quadlet_user_info.name }}"
    mode: u=rw,g=r,o=r
  notify: Restart haproxy

- name: Start haproxy service
  ansible.builtin.systemd_service:
    name: haproxy.service
    daemon_reload: true
    state: started
    scope: user
  environment:
    XDG_RUNTIME_DIR: "{{ quadlet_user_info.xdg_runtime_dir }}"
