- name: Check if trigger file exists
  ansible.builtin.stat:
    path: "{{ __fcos_upgrade_trigger_file_path }}"
  register: __fcos_upgrade_trigger_file

- name: Retrieve trigger file
  ansible.builtin.slurp:
    src: "{{ __fcos_upgrade_trigger_file_path }}"
  when: __fcos_upgrade_trigger_file.stat.exists
  register: __fcos_upgrade_trigger_file_slurp

- name: Set system upgrade facts
  ansible.builtin.set_fact:
    fcos_upgrade_requested: "{{ __fcos_upgrade_trigger_file.stat.exists | ternary(__fcos_upgrade_trigger != retrieved_trigger, false) }}"
    fcos_upgrade_trigger: "{{ __fcos_upgrade_trigger }}"
  vars:
    retrieved_trigger: "{{ __fcos_upgrade_trigger_file_slurp.content | default('') | b64decode }}"

- name: Stop zincati
  ansible.builtin.service:
    name: zincati
    state: stopped
  when: fcos_upgrade_requested
  notify: Start zincati

- name: Download ostree and rpm data
  ansible.builtin.command:
    cmd: rpm-ostree upgrade --download-only
  changed_when: true
  when: fcos_upgrade_requested
