- name: Cordon node
  ansible.builtin.command:
    cmd: "{{ __k3s_binary_dir }}/k3s kubectl cordon {{ __k3s_node_config['node-name'] }}"
  changed_when: true

- name: Drain node
  ansible.builtin.command:
    cmd: "{{ __k3s_binary_dir }}/k3s kubectl drain {{ __k3s_drain_opts }} {{ __k3s_node_config['node-name'] }}"
  register: __k3s_drain
  failed_when: __k3s_drain.rc not in [0, 1]
  changed_when: true

- name: Force drain node
  ansible.builtin.command:
    cmd: "{{ __k3s_binary_dir }}/k3s kubectl drain {{ __k3s_drain_opts }} --disable-eviction {{ __k3s_node_config['node-name'] }}"
  when: __k3s_drain.rc == 1
  changed_when: true
