- name: Stop and disable k3s service
  ansible.builtin.service:
    name: k3s-{{ __k3s_role }}
    state: stopped
    enabled: false

- name: SIGKILL k3s containerd containers
  ansible.builtin.command:
    cmd: pkill -9 -f 'k3s/data/[^/]+/bin/containerd-shim-runc'
  register: pkill_containerd_shim_runc
  changed_when: pkill_containerd_shim_runc.rc == 0
  failed_when: false
