- name: Add removed hosts
  ansible.builtin.add_host:
    name: "{{ item.key }}"
    groups: "{{ ['removed_'] | product(item.value.groups) | map('join') | list }}"
  args: "{{ item.value.hostvars }}"
  loop: "{{ (__inventory_difference_previous_inventory_file) | inventory_difference(__inventory_difference_current_inventory_file) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Add new hosts
  ansible.builtin.add_host:
    name: "{{ item.key }}"
    groups: "{{ ['new_'] | product(item.value.groups) | map('join') | list }}"
  loop: "{{ (__inventory_difference_current_inventory_file) | inventory_difference(__inventory_difference_previous_inventory_file) | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
