- name: Reset machines
  hosts: agents:servers
  gather_facts: true
  become: false
  serial: 1
  tasks:
  - name: Quadlet
    ansible.builtin.include_role:
      name: quadlet
    when: k3s_role == "server"
  - name: HAProxy
    ansible.builtin.include_role:
      name: haproxy
    vars:
      __haproxy_part: down
    when: k3s_role == "server"
  - name: Keepalived
    ansible.builtin.include_role:
      name: keepalived
      apply:
        become: true
    vars:
      __keepalived_part: down
    when: k3s_role == "server"
  - name: Reset k3s
    ansible.builtin.include_role:
      name: k3s
      apply:
        become: true
    vars:
      __k3s_part: reset
      __k3s_role: "{{ k3s_role }}"
