- name: Create keepalived quadlet volume
  ansible.builtin.copy:
    content: |
      [Volume]
    dest: "{{ quadlet_system_info.containers_dir }}/keepalived.volume"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Start keepalived volume
  ansible.builtin.systemd_service:
    name: keepalived-volume.service
    daemon_reload: true
    state: started

- name: Create keepalived conf.d directory
  ansible.builtin.file:
    path: "{{ quadlet_system_info.volumes_dir }}/systemd-keepalived/_data/conf.d"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Create keepalived config
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: "{{ quadlet_system_info.volumes_dir }}/systemd-keepalived/_data/keepalived.conf"
    owner: root
    group: root
    mode: u=rw,g=r,o=
  notify: Restart keepalived

- name: Create keepalived quadlet container
  ansible.builtin.template:
    src: keepalived.container.j2
    dest: "{{ quadlet_system_info.containers_dir }}/keepalived.container"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: Restart keepalived

- name: Start keepalived service
  ansible.builtin.systemd_service:
    name: keepalived.service
    daemon_reload: true
    state: started

- name: Set keepalived fact
  ansible.builtin.set_fact:
    keepalived_conf_dir: "{{ quadlet_system_info.volumes_dir }}/systemd-keepalived/_data/conf.d"
