- name: Restart systemd-sysctl
  ansible.builtin.service:
    name: systemd-sysctl
    state: restarted
  retries: 3
  delay: 10

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart k3s-server
  ansible.builtin.service:
    name: k3s-server
    state: restarted
  retries: 3
  delay: 10

- name: Restart k3s-agent
  ansible.builtin.service:
    name: k3s-agent
    state: restarted
  retries: 3
  delay: 10
